# Temporary configuration override for Windbreaker bot
# Source this file to apply recommended settings

export MIN_MARKET_CAP_USD="5000"
export MIN_LIQUIDITY_USD="5000"
export TRUST_TRADER_PUMPFUN="true"
export MAX_PRICE_CHANGE_1H_PCT="500"
export HARD_MAX_PRICE_CHANGE_1H_PCT="500"
export JUPITER_PRIORITY_FEE_LAMPORTS="100000"
export HARD_MIN_SOL_PER_TRADE="0.03"
export PORT="18080"

echo "Configuration overrides applied:"
echo "MIN_MARKET_CAP_USD=$MIN_MARKET_CAP_USD"
echo "MIN_LIQUIDITY_USD=$MIN_LIQUIDITY_USD"
echo "TRUST_TRADER_PUMPFUN=$TRUST_TRADER_PUMPFUN"
echo "MAX_PRICE_CHANGE_1H_PCT=$MAX_PRICE_CHANGE_1H_PCT"
echo "HARD_MAX_PRICE_CHANGE_1H_PCT=$HARD_MAX_PRICE_CHANGE_1H_PCT"
echo "JUPITER_PRIORITY_FEE_LAMPORTS=$JUPITER_PRIORITY_FEE_LAMPORTS"
echo "HARD_MIN_SOL_PER_TRADE=$HARD_MIN_SOL_PER_TRADE"
echo "PORT=$PORT"
